### ISSUE TITLE
Re-enable code coverage

### ISSUE THREAD

**Issue by dryajov** [codex-storage/nim-codex-dht#72]

**Comment by elcritch** [comment]
Finished in https://github.com/codex-storage/nim-codex-dht/pull/74

**Comment by veaceslavdoina** [comment]
@elcritch, looks like we may have similar with [nim-codex repository](https://github.com/codex-storage/nim-codex/pull/464) issue here, when `main` branch was renamed in to the `master` one

**codecov.yml**
https://github.com/codex-storage/nim-codex-dht/blob/1f27eb4aff372e6583747f2bfca1c08705a2bbfe/.github/workflows/codecov.yml#L5-L7

**ci.yml**
https://github.com/codex-storage/nim-codex-dht/blob/1f27eb4aff372e6583747f2bfca1c08705a2bbfe/.github/workflows/ci.yml#L3-L5
